import type { DocumentId } from './ids';
import type { CatalogDocument } from './types';

const zip = (n: number) => n;

/** Dokumenter utover kjernen i catalog.ts — ISO, marked, spesialdirektiver og manglende typer. */
export const EXTENDED_CATALOG: CatalogDocument[] = [
  // —— Ekstra teknisk fil / samsvar / bruker ——
  {
    id: 'bom' as DocumentId,
    label: 'Stykkliste (BOM)',
    labelEN: 'Bill of Materials',
    category: 'technical_file',
    sourceType: 'hybrid',
    required: true,
    description: 'Komplett stykkliste med artikkelnummer, leverandør og spesifikasjon',
    zipOrder: zip(6),
    outputFormat: 'docx',
    reason: 'Påkrevd for sporbarhet og vedlikehold under Maskindirektivet',
  },
  {
    id: 'calculation_report' as DocumentId,
    label: 'Beregningsrapport (FEM/styrke/last)',
    category: 'technical_file',
    sourceType: 'user_upload',
    required: false,
    description: 'Strukturberegninger, lastanalyse eller FEM/FEA',
    acceptedFormats: ['pdf'],
    zipOrder: zip(78),
    outputFormat: 'docx',
    reason: 'Dokumenterer at konstruksjonen tåler påkjenninger og laster',
  },
  {
    id: 'electrical_diagrams' as DocumentId,
    label: 'Elektriske schematics',
    category: 'technical_file',
    sourceType: 'user_upload',
    required: false,
    directive: '2014/35/EU',
    description: 'Komplett elektrisk koblingsskjema og komponentliste',
    acceptedFormats: ['pdf', 'dwg'],
    zipOrder: zip(79),
    outputFormat: 'docx',
    conditionalOn: ['hasElectric'],
    reason: 'Påkrevd for elektrisk utstyr under lavspenningsdirektivet',
  },
  {
    id: 'incorporated_declaration' as DocumentId,
    label: 'Innebygd erklæring (delvis ferdigstilt maskin)',
    category: 'conformity',
    sourceType: 'ai_generated',
    required: false,
    directive: '2006/42/EF Vedlegg II B',
    description: 'Erklæring for delvis ferdigstilte maskiner',
    zipOrder: zip(4),
    outputFormat: 'docx',
    reason: 'Kreves når maskinen leveres uferdig og ferdigstilles på stedet',
  },
  {
    id: 'type_examination' as DocumentId,
    label: 'EU-typeeksaminering',
    category: 'conformity',
    sourceType: 'user_upload',
    required: false,
    description: 'Sertifikat fra Notified Body for typeeksaminering',
    acceptedFormats: ['pdf'],
    zipOrder: zip(74),
    outputFormat: 'docx',
    reason: 'Kreves for maskiner med høy risiko eller ved valg av typeeksaminering',
  },
  {
    id: 'spare_parts_list' as DocumentId,
    label: 'Reservedelsliste',
    category: 'user_documentation',
    sourceType: 'hybrid',
    required: false,
    description: 'Anbefalte reservedeler med artikkelnummer',
    zipOrder: zip(24),
    outputFormat: 'docx',
    reason: 'Anbefalt for vedlikehold og driftssikkerhet',
  },
  {
    id: 'troubleshooting_guide' as DocumentId,
    label: 'Feilsøkingsguide',
    category: 'user_documentation',
    sourceType: 'ai_generated',
    required: false,
    description: 'Feilkoder, symptomer og tiltak',
    zipOrder: zip(25),
    outputFormat: 'docx',
    reason: 'Forenkler feilsøking og reduserer nedetid',
  },
  {
    id: 'operator_training_doc' as DocumentId,
    label: 'Opplæringsdokumentasjon for operatør',
    category: 'user_documentation',
    sourceType: 'hybrid',
    required: false,
    description: 'Opplæringsplan og kompetansekrav for operatør',
    zipOrder: zip(26),
    outputFormat: 'docx',
    reason: 'Dokumenterer at operatør er kvalifisert til sikker drift',
  },
  {
    id: 'nameplate_design' as DocumentId,
    label: 'Merkeplatedesign (CE, serienr, data)',
    category: 'safety_marking',
    sourceType: 'ai_generated',
    required: true,
    description: 'Spesifikasjon for merkeplate med CE, serienummer og tekniske data',
    zipOrder: zip(30),
    outputFormat: 'docx',
    reason: 'Påkrevd merking etter Maskindirektivet Vedlegg I §1.7.3',
  },
  {
    id: 'noise_declaration' as DocumentId,
    label: 'Støydeklarasjon',
    category: 'safety_marking',
    sourceType: 'hybrid',
    required: false,
    standard: 'EN ISO 11201',
    description: 'Deklarerte støynivåer for maskinen',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(84),
    outputFormat: 'docx',
    reason: 'Støyemisjon skal oppgis i brukerhåndbok (Vedlegg I §1.7.4)',
  },
  {
    id: 'vibration_declaration' as DocumentId,
    label: 'Vibrasjonsdeklarasjon',
    category: 'safety_marking',
    sourceType: 'hybrid',
    required: false,
    standard: 'EN ISO 5349',
    description: 'Deklarerte vibrasjonsnivåer',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(85),
    outputFormat: 'docx',
    reason: 'Hand-arm eller helkroppsvibrasjon skal dokumenteres der relevant',
  },
  {
    id: 'ndt_protocol' as DocumentId,
    label: 'NDT-protokoll',
    category: 'production_quality',
    sourceType: 'user_upload',
    required: false,
    description: 'Ikke-destruktiv testing av sveiser og kritiske søm',
    acceptedFormats: ['pdf'],
    zipOrder: zip(73),
    outputFormat: 'docx',
    reason: 'Verifiserer sveisekvalitet uten å ødelegge komponenten',
  },
  {
    id: 'calibration_certificates' as DocumentId,
    label: 'Kalibreringsbevis for måleutstyr',
    category: 'production_quality',
    sourceType: 'user_upload',
    required: false,
    description: 'Sporbar kalibrering av måleinstrumenter',
    acceptedFormats: ['pdf'],
    zipOrder: zip(86),
    outputFormat: 'docx',
    reason: 'Sikrer at måleresultater er sporbar og gyldige',
  },
  {
    id: 'production_traceability_log' as DocumentId,
    label: 'Produksjons- og sporingslogg',
    category: 'production_quality',
    sourceType: 'hybrid',
    required: false,
    description: 'Sporing av serienummer, komponenter og produksjonstrinn',
    zipOrder: zip(87),
    outputFormat: 'docx',
    reason: 'Muliggjør tilbakekalling og kvalitetssporing',
  },
  {
    id: 'pressure_test_protocol' as DocumentId,
    label: 'Trykktestprotokoll',
    category: 'production_quality',
    sourceType: 'hybrid',
    required: false,
    description: 'Dokumentert trykktest av trykksatt utstyr',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(88),
    outputFormat: 'docx',
    conditionalOn: ['hasPressure'],
    reason: 'Verifiserer at trykksatt utstyr tåler driftstrykk',
  },
  {
    id: 'load_test_report' as DocumentId,
    label: 'Belastningsprøvingsrapport',
    category: 'production_quality',
    sourceType: 'user_upload',
    required: false,
    description: 'Statisk og dynamisk prøvelast for løfteinnretninger',
    acceptedFormats: ['pdf'],
    zipOrder: zip(89),
    outputFormat: 'docx',
    conditionalOn: ['hasLifting'],
    reason: 'Løfteinnretninger krever dokumentert belastningsprøving',
  },

  // —— ISO 9001 ——
  {
    id: 'quality_manual' as DocumentId,
    label: 'Kvalitetshåndbok',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Overordnet kvalitetsstyringssystem',
    requiredContent: ['Kvalitetspolicy', 'Organisasjonskart', 'Prosessoversikt', 'Omfangsbeskrivelse'],
    acceptedFormats: ['pdf'],
    zipOrder: zip(100),
    outputFormat: 'docx',
    reason: 'Kjernekrav i ISO 9001 for dokumentert kvalitetsstyringssystem',
  },
  {
    id: 'design_control_procedure' as DocumentId,
    label: 'Prosedyre for designkontroll',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Prosess for design og utvikling',
    requiredContent: ['Designinngang', 'Designutgang', 'Designverifikasjon', 'Designvalidering', 'Designendringer'],
    acceptedFormats: ['pdf'],
    zipOrder: zip(101),
    outputFormat: 'docx',
    reason: 'ISO 9001 krever kontrollert designprosess for produktutvikling',
  },
  {
    id: 'document_control_procedure' as DocumentId,
    label: 'Prosedyre for dokumentstyring',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Kontroll av dokumenter og data',
    acceptedFormats: ['pdf'],
    zipOrder: zip(102),
    outputFormat: 'docx',
    reason: 'Sikrer at kun gyldige dokumenter er i bruk',
  },
  {
    id: 'supplier_evaluation' as DocumentId,
    label: 'Leverandørevaluering og godkjenning',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Kriterier og register for godkjente leverandører',
    acceptedFormats: ['pdf'],
    zipOrder: zip(103),
    outputFormat: 'docx',
    reason: 'ISO 9001 krever kontroll av innkjøpte produkter og tjenester',
  },
  {
    id: 'nonconformance_procedure' as DocumentId,
    label: 'Avvikshåndteringsprosedyre',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Håndtering av avvik og ikke-konforme produkter',
    acceptedFormats: ['pdf'],
    zipOrder: zip(104),
    outputFormat: 'docx',
    reason: 'Systematisk håndtering av avvik er et grunnkrav i ISO 9001',
  },
  {
    id: 'corrective_action' as DocumentId,
    label: 'Korrigerende og forebyggende tiltak (CAPA)',
    category: 'quality_management',
    sourceType: 'hybrid',
    required: true,
    isoScope: ['iso_9001'],
    description: 'CAPA-register og oppfølging',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(105),
    outputFormat: 'docx',
    reason: 'Adresserer rotårsaker og forebygger gjentakelse',
  },
  {
    id: 'internal_audit_plan' as DocumentId,
    label: 'Internrevisjonsplan og -rapport',
    category: 'quality_management',
    sourceType: 'hybrid',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Planlagte internrevisjoner med funn',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(106),
    outputFormat: 'docx',
    reason: 'Verifiserer at kvalitetssystemet fungerer etter hensikten',
  },
  {
    id: 'management_review' as DocumentId,
    label: 'Ledelsens gjennomgang',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Referat fra ledelsens periodiske gjennomgang',
    acceptedFormats: ['pdf'],
    zipOrder: zip(107),
    outputFormat: 'docx',
    reason: 'Ledelsen skal evaluere systemets egnethet og tilstrekkelighet',
  },
  {
    id: 'quality_objectives' as DocumentId,
    label: 'Kvalitetsmål og måleplan',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001'],
    description: 'Målbare kvalitetsmål med oppfølging',
    acceptedFormats: ['pdf'],
    zipOrder: zip(108),
    outputFormat: 'docx',
    reason: 'Kvalitetsmål skal være målbare og overvåket',
  },
  {
    id: 'customer_satisfaction' as DocumentId,
    label: 'Kundetilfredshetsmåling',
    category: 'quality_management',
    sourceType: 'hybrid',
    required: false,
    isoScope: ['iso_9001'],
    description: 'Resultater fra kundetilfredshet',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(109),
    outputFormat: 'docx',
    reason: 'Måler om kundens forventninger er oppfylt',
  },
  {
    id: 'training_records' as DocumentId,
    label: 'Kompetanse- og opplæringsregister',
    category: 'quality_management',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_9001', 'iso_45001'],
    description: 'Dokumentert kompetanse for ansatte',
    acceptedFormats: ['pdf'],
    zipOrder: zip(110),
    outputFormat: 'docx',
    reason: 'Sikrer at personell har nødvendig kompetanse',
  },
  {
    id: 'itp' as DocumentId,
    label: 'Inspeksjons- og testplan (ITP)',
    category: 'quality_management',
    sourceType: 'hybrid',
    required: false,
    isoScope: ['iso_9001'],
    description: 'Plan for inspeksjon og testing under produksjon',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(111),
    outputFormat: 'docx',
    reason: 'Definerer kontrollpunkter i produksjonsprosessen',
  },

  // —— ISO 14001 ——
  {
    id: 'environmental_policy' as DocumentId,
    label: 'Miljøpolicy',
    category: 'environmental',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_14001'],
    description: 'Bedriftens forpliktelse til miljøstyring',
    acceptedFormats: ['pdf'],
    zipOrder: zip(120),
    outputFormat: 'docx',
    reason: 'Overordnet forpliktelse til miljøforbedring (ISO 14001)',
  },
  {
    id: 'environmental_aspects' as DocumentId,
    label: 'Miljøaspekter og -virkninger',
    category: 'environmental',
    sourceType: 'hybrid',
    required: true,
    isoScope: ['iso_14001'],
    description: 'Identifiserte miljøaspekter med betydning',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(121),
    outputFormat: 'docx',
    reason: 'Grunnlag for prioritering av miljøtiltak',
  },
  {
    id: 'legal_register_env' as DocumentId,
    label: 'Lovregister (miljø)',
    category: 'environmental',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_14001'],
    description: 'Oversikt over gjeldende miljølovgivning',
    acceptedFormats: ['pdf'],
    zipOrder: zip(122),
    outputFormat: 'docx',
    reason: 'Sikrer etterlevelse av miljøkrav',
  },
  {
    id: 'waste_management_plan' as DocumentId,
    label: 'Avfallshåndteringsplan',
    category: 'environmental',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_14001'],
    description: 'Sortering, håndtering og deponering av avfall',
    acceptedFormats: ['pdf'],
    zipOrder: zip(123),
    outputFormat: 'docx',
    reason: 'Kontrollerer miljøpåvirkning fra avfall',
  },
  {
    id: 'energy_consumption_log' as DocumentId,
    label: 'Energiforbrukslogg',
    category: 'environmental',
    sourceType: 'hybrid',
    required: false,
    isoScope: ['iso_14001'],
    description: 'Måling og oppfølging av energiforbruk',
    acceptedFormats: ['pdf', 'xlsx'],
    zipOrder: zip(124),
    outputFormat: 'docx',
    reason: 'Støtter energireduserende tiltak',
  },
  {
    id: 'epd' as DocumentId,
    label: 'Miljødeklarasjon (EPD)',
    category: 'environmental',
    sourceType: 'user_upload',
    required: false,
    isoScope: ['iso_14001'],
    description: 'Type III miljødeklarasjon for produktet',
    acceptedFormats: ['pdf'],
    zipOrder: zip(125),
    outputFormat: 'docx',
    reason: 'Dokumenterer produktets miljøpåvirkning over livssyklus',
  },
  {
    id: 'reach_declaration' as DocumentId,
    label: 'REACH-samsvarserklæring',
    category: 'product_compliance',
    sourceType: 'ai_generated',
    required: false,
    isoScope: ['iso_14001'],
    description: 'Erklæring om kjemikaliesamsvar (REACH)',
    zipOrder: zip(126),
    outputFormat: 'docx',
    reason: 'Dokumenterer at produktet oppfyller REACH-krav',
  },
  {
    id: 'rohs_declaration' as DocumentId,
    label: 'RoHS-samsvarserklæring',
    category: 'product_compliance',
    sourceType: 'ai_generated',
    required: false,
    isoScope: ['iso_14001'],
    description: 'Erklæring om begrensning av farlige stoffer',
    zipOrder: zip(127),
    outputFormat: 'docx',
    reason: 'Elektronikk og komponenter må oppfylle RoHS',
  },
  {
    id: 'weee_registration' as DocumentId,
    label: 'WEEE-registrering',
    category: 'product_compliance',
    sourceType: 'user_upload',
    required: false,
    isoScope: ['iso_14001'],
    description: 'Registrering som produsent av EE-avfall',
    acceptedFormats: ['pdf'],
    zipOrder: zip(128),
    outputFormat: 'docx',
    reason: 'Påkrevd for elektrisk og elektronisk utstyr på markedet',
  },

  // —— ISO 45001 ——
  {
    id: 'hse_policy' as DocumentId,
    label: 'HMS-policy',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Bedriftens forpliktelse til arbeidsmiljø',
    acceptedFormats: ['pdf'],
    zipOrder: zip(130),
    outputFormat: 'docx',
    reason: 'Overordnet HMS-forpliktelse (ISO 45001)',
  },
  {
    id: 'hse_risk_assessment' as DocumentId,
    label: 'HMS-risikovurdering (arbeidsplassvurdering)',
    category: 'health_safety',
    sourceType: 'hybrid',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Risikovurdering av arbeidsoppgaver og arbeidsplass',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(131),
    outputFormat: 'docx',
    reason: 'Identifiserer og kontrollerer arbeidsrelaterte farer',
  },
  {
    id: 'legal_register_hse' as DocumentId,
    label: 'Lovregister (HMS)',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Oversikt over gjeldende HMS-lovgivning',
    acceptedFormats: ['pdf'],
    zipOrder: zip(132),
    outputFormat: 'docx',
    reason: 'Sikrer etterlevelse av arbeidsmiljøkrav',
  },
  {
    id: 'incident_procedure' as DocumentId,
    label: 'Prosedyre for hendelse og ulykke',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Rapportering og oppfølging av hendelser',
    acceptedFormats: ['pdf'],
    zipOrder: zip(133),
    outputFormat: 'docx',
    reason: 'Systematisk læring fra uønskede hendelser',
  },
  {
    id: 'ppe_register' as DocumentId,
    label: 'Verneutstyrsregister (PPE)',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Oversikt over påkrevd verneutstyr',
    acceptedFormats: ['pdf'],
    zipOrder: zip(134),
    outputFormat: 'docx',
    reason: 'Sikrer riktig verneutstyr for alle arbeidsoppgaver',
  },
  {
    id: 'lockout_tagout' as DocumentId,
    label: 'LOTO-prosedyre (lås og merk)',
    category: 'health_safety',
    sourceType: 'hybrid',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Prosedyre for sikker isolering ved vedlikehold',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(135),
    outputFormat: 'docx',
    reason: 'Forhindrer utilsiktet oppstart under vedlikehold',
  },
  {
    id: 'safety_data_sheets' as DocumentId,
    label: 'Sikkerhetsdatablader (SDS/HMS-blader)',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'SDS for kjemikalier brukt i produksjon',
    acceptedFormats: ['pdf'],
    zipOrder: zip(136),
    outputFormat: 'docx',
    reason: 'Påkrevd informasjon om kjemikalier på arbeidsplassen',
  },
  {
    id: 'emergency_plan' as DocumentId,
    label: 'Beredskapsplan',
    category: 'health_safety',
    sourceType: 'user_upload',
    required: true,
    isoScope: ['iso_45001'],
    description: 'Tiltak ved brann, ulykke og nødsituasjoner',
    acceptedFormats: ['pdf'],
    zipOrder: zip(137),
    outputFormat: 'docx',
    reason: 'Forbereder organisasjonen på nødsituasjoner',
  },
  {
    id: 'hse_audit_report' as DocumentId,
    label: 'HMS-revisjonsrapport',
    category: 'health_safety',
    sourceType: 'hybrid',
    required: false,
    isoScope: ['iso_45001'],
    description: 'Resultater fra intern HMS-revisjon',
    acceptedFormats: ['pdf', 'docx'],
    zipOrder: zip(138),
    outputFormat: 'docx',
    reason: 'Verifiserer at HMS-systemet fungerer',
  },

  // —— Spesialdirektiver ——
  {
    id: 'atex_cert' as DocumentId,
    label: 'ATEX-sertifikat (2014/34/EU)',
    category: 'special_directive',
    sourceType: 'user_upload',
    required: true,
    directive: '2014/34/EU',
    description: 'Typeeksaminering for utstyr i eksplosiv atmosfære',
    acceptedFormats: ['pdf'],
    zipOrder: zip(140),
    outputFormat: 'docx',
    conditionalOn: ['hasAtex'],
    reason: 'Påkrevd for utstyr i ATEX-soner',
  },
  {
    id: 'atex_manual' as DocumentId,
    label: 'ATEX bruksveiledning',
    category: 'special_directive',
    sourceType: 'hybrid',
    required: true,
    directive: '2014/34/EU',
    description: 'Sikker bruk i eksplosiv atmosfære',
    zipOrder: zip(141),
    outputFormat: 'docx',
    conditionalOn: ['hasAtex'],
    reason: 'Operatør må kjenne begrensninger i Ex-områder',
  },
  {
    id: 'ped_technical_file' as DocumentId,
    label: 'PED teknisk fil (2014/68/EU)',
    category: 'special_directive',
    sourceType: 'user_upload',
    required: true,
    directive: '2014/68/EU',
    description: 'Teknisk dokumentasjon for trykksatt utstyr',
    acceptedFormats: ['pdf'],
    zipOrder: zip(142),
    outputFormat: 'docx',
    conditionalOn: ['hasPressure'],
    reason: 'Trykksatt utstyr under PED krever teknisk fil',
  },
  {
    id: 'emc_report' as DocumentId,
    label: 'EMC-testrapport (2014/30/EU)',
    category: 'special_directive',
    sourceType: 'user_upload',
    required: true,
    directive: '2014/30/EU',
    description: 'EMC-test fra akkreditert laboratorium',
    acceptedFormats: ['pdf'],
    zipOrder: zip(143),
    outputFormat: 'docx',
    conditionalOn: ['hasElectric'],
    reason: 'Elektrisk utstyr må oppfylle EMC-direktivet',
  },
  {
    id: 'red_cert' as DocumentId,
    label: 'RED-sertifikat (2014/53/EU)',
    category: 'special_directive',
    sourceType: 'user_upload',
    required: false,
    directive: '2014/53/EU',
    description: 'Sertifikat for radio- og trådløst utstyr',
    acceptedFormats: ['pdf'],
    zipOrder: zip(144),
    outputFormat: 'docx',
    conditionalOn: ['hasWireless'],
    reason: 'Trådløst utstyr faller under RED-direktivet',
  },
  {
    id: 'machinery_reg_checklist' as DocumentId,
    label: 'Maskinforordning 2022/2380 sjekkliste',
    category: 'special_directive',
    sourceType: 'ai_generated',
    required: false,
    description: 'Sjekkliste for nye krav i oppdatert maskinforordning',
    zipOrder: zip(145),
    outputFormat: 'docx',
    conditionalOn: ['after2027'],
    reason: 'Nye krav gjelder fra 2027 under oppdatert maskinforordning',
  },
  {
    id: 'cybersecurity_assessment' as DocumentId,
    label: 'Cybersikkerhetsrisikovurdering',
    category: 'special_directive',
    sourceType: 'hybrid',
    required: false,
    description: 'Risikovurdering for digitale kontrollsystemer',
    zipOrder: zip(146),
    outputFormat: 'docx',
    conditionalOn: ['hasDigitalControl', 'after2027'],
    reason: 'Digitale maskiner krever cybersikkerhetsvurdering fra 2027',
  },
  {
    id: 'ai_system_doc' as DocumentId,
    label: 'AI-systemdokumentasjon (EU AI Act)',
    category: 'special_directive',
    sourceType: 'hybrid',
    required: false,
    description: 'Dokumentasjon for AI-baserte sikkerhetsfunksjoner',
    zipOrder: zip(147),
    outputFormat: 'docx',
    conditionalOn: ['hasAI'],
    reason: 'AI-systemer i maskiner kan kreve dokumentasjon under AI Act',
  },
  {
    id: 'atex_documentation' as DocumentId,
    label: 'ATEX-dokumentasjon (samlet)',
    category: 'special_directive',
    sourceType: 'user_upload',
    required: false,
    directive: '2014/34/EU',
    description: 'Samlet ATEX-dokumentasjonspakke',
    acceptedFormats: ['pdf', 'zip'],
    zipOrder: zip(148),
    outputFormat: 'docx',
    conditionalOn: ['hasAtex'],
    reason: 'Samler ATEX-krav for eksplosive atmosfærer',
  },
  {
    id: 'low_voltage_checklist' as DocumentId,
    label: 'Lavspennings-sjekkliste',
    category: 'special_directive',
    sourceType: 'ai_generated',
    required: false,
    directive: '2014/35/EU',
    description: 'Sjekkliste for lavspenningsdirektivet',
    zipOrder: zip(149),
    outputFormat: 'docx',
    conditionalOn: ['hasElectric'],
    reason: 'Elektrisk utstyr under 1000 V AC skal oppfylle LVD',
  },

  // —— Markedsspesifikke ——
  {
    id: 'ukca_declaration' as DocumentId,
    label: 'UKCA Declaration of Conformity',
    category: 'market_specific',
    sourceType: 'ai_generated',
    required: false,
    description: 'Samsvarserklæring for Storbritannia',
    zipOrder: zip(150),
    outputFormat: 'docx',
    conditionalOn: ['marketUK'],
    reason: 'UK-marked krever UKCA-erklæring etter Brexit',
  },
  {
    id: 'ul_listing' as DocumentId,
    label: 'UL-sertifisering',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'UL-listing for USA-markedet',
    acceptedFormats: ['pdf'],
    zipOrder: zip(151),
    outputFormat: 'docx',
    conditionalOn: ['marketUSA'],
    reason: 'USA-markedet krever ofte UL-godkjenning',
  },
  {
    id: 'osha_sdoc' as DocumentId,
    label: 'OSHA-samsvarsdokumentasjon',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'OSHA-krav for arbeidsmiljø og maskinsikkerhet i USA',
    acceptedFormats: ['pdf'],
    zipOrder: zip(152),
    outputFormat: 'docx',
    conditionalOn: ['marketUSA'],
    reason: 'USA-arbeidsmiljølov (OSHA) gjelder for installasjon og drift',
  },
  {
    id: 'csa_documentation' as DocumentId,
    label: 'CSA-sertifisering',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'CSA-godkjenning for Canada',
    acceptedFormats: ['pdf'],
    zipOrder: zip(153),
    outputFormat: 'docx',
    conditionalOn: ['marketCanada'],
    reason: 'Canada-markedet krever CSA-sertifisering',
  },
  {
    id: 'rcm_declaration' as DocumentId,
    label: 'RCM Declaration (Australia/NZ)',
    category: 'market_specific',
    sourceType: 'ai_generated',
    required: false,
    description: 'Regulatory Compliance Mark for Australia og New Zealand',
    zipOrder: zip(154),
    outputFormat: 'docx',
    conditionalOn: ['marketAustralia'],
    reason: 'RCM er påkrevd for elektrisk utstyr i Australia/NZ',
  },
  {
    id: 'eac_cert' as DocumentId,
    label: 'EAC-sertifikat (Eurasia)',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'Eurasian Conformity for EAEU-markedet',
    acceptedFormats: ['pdf'],
    zipOrder: zip(155),
    outputFormat: 'docx',
    conditionalOn: ['marketEurasia'],
    reason: 'EAEU-markedet krever EAC-sertifisering',
  },
  {
    id: 'ccc_cert' as DocumentId,
    label: 'CCC-sertifikat (Kina)',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'China Compulsory Certification',
    acceptedFormats: ['pdf'],
    zipOrder: zip(156),
    outputFormat: 'docx',
    conditionalOn: ['marketChina'],
    reason: 'Kina-markedet krever CCC for mange produkttyper',
  },
  {
    id: 'inmetro_cert' as DocumentId,
    label: 'INMETRO-sertifikat (Brasil)',
    category: 'market_specific',
    sourceType: 'user_upload',
    required: false,
    description: 'Brasiliansk samsvarssertifikat',
    acceptedFormats: ['pdf'],
    zipOrder: zip(157),
    outputFormat: 'docx',
    conditionalOn: ['marketBrazil'],
    reason: 'Brasil-markedet krever INMETRO-godkjenning',
  },
];
